### ISSUE TITLE
Setting Day of the Week

### ISSUE THREAD

**Issue by anuradhawick** [tanakamasayuki/I2C_BM8563#5]
Hi,

I am using M5Stick C Plus. I want to know how the date setting works.

Is Monday = 1 ?
Is January = 1?

I assume the year and day of the month are set as they are.

Help is appreciated. Thanks

**Comment by tanakamasayuki** [comment]
HI!

https://lang-ship.com/blog/work/m5stickc-rtc-ntp/

Sorry for the Japanese.
Mon is 1.

```c
  static const char *wd[7] = {"Sun","Mon","Tue","Wed","Thr","Fri","Sat"};

  M5.Lcd.printf("Week: %s\n", wd[RTC_DateStruct.WeekDay]);
```

# Datasheet
https://www.belling.com.cn/media/file_object/bel_product/BM8563/datasheet/BM8563_V1.1_cn.pdf

![Week](https://user-images.githubusercontent.com/10301363/115170705-408b3600-a0fc-11eb-99de-662cd889ad7b.png)

星期日 = Sunday

**Comment by tanakamasayuki** [comment]
Hi.

https://github.com/tanakamasayuki/I2C_BM8563/blob/master/examples/BM8563_SET_NTP/BM8563_SET_NTP.ino

```c
  // Print RTC
  Serial.printf("%04d/%02d/%02d %02d:%02d:%02d\n",
                dateStruct.year,
                dateStruct.month,
                dateStruct.date,
                timeStruct.hours,
                timeStruct.minutes,
                timeStruct.seconds
               );
```

The numbers are the values that can be output.

2021-04-19(today)
dateStruct.year = 2021
dateStruct.month = 4
dateStruct.date = 19

# Week
https://lang-ship.com/blog/work/m5stickc-rtc-ntp/
```c
  static const char *wd[7] = {"Sun","Mon","Tue","Wed","Thr","Fri","Sat"};
  M5.Lcd.printf("Week: %s\n", wd[RTC_DateStruct.WeekDay]);
```

Sun = 0

**Comment by anuradhawick** [comment]
Thanks! Much wanted help. Cheers.
