### ISSUE TITLE
int I2C_BM8563::SetAlarmIRQ(const I2C_BM8563_TimeTypeDef &I2C_BM8563_TimeStruct)

### ISSUE THREAD

**Issue by andygoldenson** [tanakamasayuki/I2C_BM8563#6]
In: 
int I2C_BM8563::SetAlarmIRQ(const I2C_BM8563_TimeTypeDef &I2C_BM8563_TimeStruct)

  out_buf[2] = 0x00;
  out_buf[3] = 0x00;

Should be:

  out_buf[2] = 0x80;
  out_buf[3] = 0x80;

0x80 disables those alarms since they're not used.
They were initialized correctly at the top, but then reset incorrectly later.

Andy

**Comment by tanakamasayuki** [comment]
https://github.com/tanakamasayuki/I2C_BM8563/releases/tag/1.0.4

Fixed.
